---
- set_fact:
    preserve_dap: true
  tags: [ 'never', 'preserve_dap' ]

- name: template xml 
  template:
    src: "dap_xml.j2"
    dest: "{{ xml_src }}"
  vars:
    ansible_python_interpreter: "{{ python_interpreter }}" # this is required to avoid selinux python binding errors

- name: copy xml to firewall
  net_put:
    src: "{{ xml_src }}"
    dest: "{{ xml_dest }}"

- name: clear configured records on asa
  asa_config:
    lines: "clear conf dynamic-access-policy-record"
  when: preserve_dap is not defined

- name: configure dap records on asa
  asa_config:
    src: "dap.j2"

- name: configure default access policy record on asa
  asa_config:
    parents:
      - "dynamic-access-policy-record DfltAccessPolicy" 
    lines:
      - 'user-message "{{ dap_default_message }}"'
      - 'action {{ dap_default_action }}'
    replace: block

- name: activate new dap config 
  asa_command:
    commands: "dynamic-access-policy-config activate"
